# Form implementation generated from reading ui file 'main_layout.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photoRadioBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.photoRadioBtn.setEnabled(True)
        self.photoRadioBtn.setGeometry(QtCore.QRect(120, 190, 99, 20))
        self.photoRadioBtn.setStyleSheet("font: 11pt \"Sans Serif\";")
        self.photoRadioBtn.setChecked(True)
        self.photoRadioBtn.setObjectName("photoRadioBtn")
        self.videoRadioBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.videoRadioBtn.setGeometry(QtCore.QRect(120, 220, 99, 20))
        self.videoRadioBtn.setStyleSheet("font: 11pt \"Sans Serif\";")
        self.videoRadioBtn.setObjectName("videoRadioBtn")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 420, 781, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startVideoBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startVideoBtn.setAutoFillBackground(False)
        self.startVideoBtn.setStyleSheet("background-color: rgb(126, 255, 117);\n"
"color:rgb(0, 0, 0);\n"
"font: 11pt \"Sans Serif\";")
        self.startVideoBtn.setObjectName("startVideoBtn")
        self.horizontalLayout.addWidget(self.startVideoBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.capturePhotoBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.capturePhotoBtn.setStyleSheet("background-color: rgb(201, 199, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 700 13pt \"Open Sans\";")
        self.capturePhotoBtn.setObjectName("capturePhotoBtn")
        self.horizontalLayout.addWidget(self.capturePhotoBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.stopVideoBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopVideoBtn.setStyleSheet("background-color:rgb(255, 0, 0);\n"
"color:rgb(0, 0, 0);\n"
"font: 11pt \"Sans Serif\";\n"
"")
        self.stopVideoBtn.setObjectName("stopVideoBtn")
        self.horizontalLayout.addWidget(self.stopVideoBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(120, 280, 541, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.savePathBox = QtWidgets.QPlainTextEdit(self.groupBox)
        self.savePathBox.setGeometry(QtCore.QRect(100, 35, 300, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePathBox.sizePolicy().hasHeightForWidth())
        self.savePathBox.setSizePolicy(sizePolicy)
        self.savePathBox.setAcceptDrops(True)
        self.savePathBox.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.savePathBox.setPlainText("")
        self.savePathBox.setCenterOnScroll(True)
        self.savePathBox.setObjectName("savePathBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.label.setStyleSheet("font: 11pt \"Sans Serif\";")
        self.label.setObjectName("label")
        self.editBtn = QtWidgets.QPushButton(self.groupBox)
        self.editBtn.setGeometry(QtCore.QRect(440, 35, 80, 22))
        self.editBtn.setStyleSheet("font: 11pt \"Sans Serif\";")
        self.editBtn.setObjectName("editBtn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 301, 61))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgb(255, 112, 87);\n"
"font: 600 italic 30pt \"Open Sans\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.photoRadioBtn.setText(_translate("MainWindow", "Photo"))
        self.videoRadioBtn.setText(_translate("MainWindow", "Video"))
        self.startVideoBtn.setText(_translate("MainWindow", "Start"))
        self.capturePhotoBtn.setText(_translate("MainWindow", "Click Photo"))
        self.stopVideoBtn.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Save to"))
        self.editBtn.setText(_translate("MainWindow", "Edit"))
        self.label_2.setText(_translate("MainWindow", "LibreCam"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
